/*----- PROTECTED REGION ID(SFinderBroker::DynAttrUtils.cpp) ENABLED START -----*/
static const char *RcsId = "$Id:  $";
//=============================================================================
//
// file :        SFinderBrokerDynAttrUtils.cpp
//
// description : Dynamic attributes utilities file for the SFinderBroker class
//
// project :     
//
// This file is part of Tango device class.
// 
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
// 
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
// 
// $Author:  $
//
// $Revision:  $
// $Date:  $
//
// $HeadURL:  $
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include <SFinderBroker.h>
#include <SFinderBrokerClass.h>

/*----- PROTECTED REGION END -----*/	//	SFinderBroker::DynAttrUtils.cpp

//================================================================
//  Attributes managed is:
//================================================================
//  dynStringAttr  |  Tango::DevString	Scalar
//================================================================

//	For compatibility reason, this file (SFinderBrokerDynAttrUtils)
//	manage also the dynamic command utilities.
//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//================================================================

namespace SFinderBroker_ns
{
//=============================================================
//	Add/Remove dynamic attribute methods
//=============================================================

//--------------------------------------------------------
/**
 *	Add a dynStringAttr dynamic attribute.
 *
 *  parameter attname: attribute name to be cretated and added.
 */
//--------------------------------------------------------
void SFinderBroker::add_dynStringAttr_dynamic_attribute(string attname)
{
	//	Attribute : dynStringAttr
	dynStringAttrAttrib	*dynstringattr = new dynStringAttrAttrib(attname);
	Tango::UserDefaultAttrProp	dynstringattr_prop;
	//	description	not set for dynStringAttr
	//	label	not set for dynStringAttr
	//	unit	not set for dynStringAttr
	//	standard_unit	not set for dynStringAttr
	//	display_unit	not set for dynStringAttr
	//	format	not set for dynStringAttr
	//	max_value	not set for dynStringAttr
	//	min_value	not set for dynStringAttr
	//	max_alarm	not set for dynStringAttr
	//	min_alarm	not set for dynStringAttr
	//	max_warning	not set for dynStringAttr
	//	min_warning	not set for dynStringAttr
	//	delta_t	not set for dynStringAttr
	//	delta_val	not set for dynStringAttr
	
	/*----- PROTECTED REGION ID(SFinderBroker::att_dynStringAttr_dynamic_attribute) ENABLED START -----*/
	
	
	/*----- PROTECTED REGION END -----*/	//	SFinderBroker::att_dynStringAttr_dynamic_attribute
	dynstringattr->set_default_properties(dynstringattr_prop);
	//	Not Polled
	dynstringattr->set_disp_level(Tango::OPERATOR);
	//	Not Memorized
	char array[1];
	array[0] = '\0';
	dynStringAttr_data.insert(make_pair(attname, array));
	add_attribute(dynstringattr);
}
//--------------------------------------------------------
/**
 *	remove a dynStringAttr dynamic attribute.
 *
 *  parameter attname: attribute name to be removed.
 */
//--------------------------------------------------------
void SFinderBroker::remove_dynStringAttr_dynamic_attribute(string attname)
{
	remove_attribute(attname, true);
	map<string,Tango::DevString>::iterator ite;
    if ((ite=dynStringAttr_data.find(attname))!=dynStringAttr_data.end())
    {
    	/*----- PROTECTED REGION ID(SFinderBroker::remove_dynStringAttr_dynamic_attribute) ENABLED START -----*/
    	
    	/*----- PROTECTED REGION END -----*/	//	SFinderBroker::remove_dynStringAttr_dynamic_attribute
		dynStringAttr_data.erase(ite);
	}
}


//============================================================
//	Tool methods to get pointer on attribute data buffer 
//============================================================
//--------------------------------------------------------
/**
 *	Return a pointer on dynStringAttr data.
 *
 *  parameter attname: the specified attribute name.
 */
//--------------------------------------------------------
Tango::DevString *SFinderBroker::get_dynStringAttr_data_ptr(string &name)
{
	map<string,Tango::DevString>::iterator ite;
    if ((ite=dynStringAttr_data.find(name))==dynStringAttr_data.end())
    {
		TangoSys_OMemStream	tms;
		tms << "Dynamic attribute " << name << " has not been created";
		Tango::Except::throw_exception(
					(const char *)"ATTRIBUTE_NOT_FOUND",
					tms.str().c_str(),
					(const char *)"SFinderBroker::get_dynStringAttr_data_ptr()");
    }
	return  &(ite->second);
}


//=============================================================
//	Add/Remove dynamic command methods
//=============================================================


} //	namespace
